#!/bin/sh
#
# Tiny GTK interface to SliTaz Live USB tool aka TazUSB.
#
# Copyright (C) 2012 SliTaz GNU/Linux - GNU gpl v2
#
# Authors : Christophe Lincoln <pankso@slitaz.org>
#

# TazUSBbox is only for root.
if test $(id -u) != 0 ; then
	exec tazbox su tazusb-box
	exit 0
fi

title="TazUSB Box"
icon="usb-creator"
opts="--image=usb-creator --image-on-top --width=520 --center --on-top"

# I18n
. /usr/bin/gettext.sh
TEXTDOMAIN='tazusb-box'
export TEXTDOMAIN

# Main text information
info="$(gettext "<b>Generate SliTaz LiveUSB media and boot in RAM!</b> \
Insert a LiveCD into the cdrom drive or use a local ISO image, select \
the correct device and press OK.")
"

#
# Functions
#

# Nice GTK output for commands.
output() {
	yad --text-info $opts --text="<b>$title</b>" \
		--height=260 --title="$title" --window-icon=$icon \
		--tail --margins=4 --button="Reboot:reboot" --button="gtk-close:0"
}

list_devices() {
	if [ -d /proc/scsi/usb-storage ]; then
		dev="$(blkid | cut -d ":" -f 1)"
		echo $dev | sed s'/ /!/'g
	else
		gettext "No USB media found"
	fi
}

# Main GUI box function with pure Yad spec
tazusb_main() {
	yad --form $opts --text="$info" \
		--title="$title" --height=200 \
		--field="$(gettext "ISO Image:")":FL \
		--field="$(gettext "USB Media:")":CB \
		" " "$(list_devices)"
}

# Handler
tazusb() {
	# Store box results
	main=$(tazusb_main)
	ret=$?
	# Deal with --button values
	case $ret in
		1) exit 0 ;;
		*) continue ;;
	esac
	# Deal with $main values. Exit if any device.
	dev=$(echo $main | cut -d "|" -f 2)
	if ! echo $dev | grep -q /dev; then
		exit 0
	fi 
	if echo "$main" | grep -q ".iso|"; then
		iso=$(echo $main | cut -d "|" -f 1)
		yes "" | /usr/bin/tazusb gen-iso2usb $iso $dev --raw-out | output
		exit 0
	else
		yes "" | /usr/bin/tazusb gen-liveusb $dev --raw-out | output
	fi
}

#
# Script commands
#

case "$1" in
	usage)
		echo "Usage: $(basename $0) [command]" ;;
	*) 
		tazusb ;;
esac

exit 0

